dbs/dbs/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gallery.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbs/gallery/urls.py
from django.conf.urls import url
from . import views

app_name = 'gallery'

urlpatterns = [
    url(r'^galeria/$', views.home, name='gallery'),
    url(r'^agregar/$', views.add_image, name='add'),
]

dbs/gallery/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=48)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return '%s' % self.name


class Card(models.Model):
    name = models.CharField(max_length=48)
    description = models.TextField(null=True, blank=True, default='Describe la tarjeta')
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category)
    image = models.ImageField(default='', upload_to='cards')

    class Meta:
        verbose_name = 'Tarjeta'
        verbose_name_plural = 'Tarjetas'

    def __str__(self):
        return '%s' % self.name

dbs/gallery/forms.py
from django.forms import  ModelForm
from .models import Card

dbs/gallery/views.py
from django.shortcuts import render

from django.http import  JsonResponse
from .models import Card


def home(request):

    if request.method == 'POST':
        id_card = request.POST['id_card']
        card = Card.objects.get(id=id_card)
        json_card = {
            'HOLA': 'K ASE?'
        }
        print(request.POST)
        return JsonResponse(json_card)


    template = "home.html"
    cards = Card.objects.all()
    context = {
        'cards': cards
    }
    return render(request, template, context)


def add_image(request):
    template = "agregar.html"
    cards = Card.objects.all()
    context = {
        'cards': cards
    }
    return render(request, template, context)

dbs/gallery/templates/agregar.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>DBS - Agergar Tarjeta</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/master.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Agregar tarjeta</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'gallery:add' %}">Agregar Tarjeta</a>
      </li>
    </ul>
  </div>
</nav>

<main>
  <div class="container">
    <div class="row">
      {% for card in cards %}
        <div class="col">
          <div class="card my-2" style="width: 20rem;">
            <h4 class="card-title">{{ card.name }}</h4>
            {% if card.image %}
              <img class="card-img-top" src="{{ card.image.url }}" alt="Card image cap">
            {% else %}
              <img class="card-img-top" src="{% static 'images/dbs.jpg' %}" alt="Card image cap">
            {% endif %}
            <div class="card-body">
              <p class="card-text">{{ card.description }}</p>
            </div>
            <input type="hidden" value="{{ card.pk }}">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
              Launch demo modal
            </button>
          </div>
        </div>
      {% endfor %}
    </div>





  </div>


  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}


            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <input type="checkbox" class="form-check-input">
                Check me out
              </label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
</main>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

<script>

    // using jQuery
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    $(document).ready(function() {
        $.ajax({
            url: '{% url "gallery:add" %}',
            type: 'POST',
            traditional: true,
            data: {
                'param1': id_card,
                casrfmiddlewaretoken: getCookie("csrftoken")

            },
            dataType: 'jsonp',
            success: function(result) {
                console.log();
            }
        });
    });
</script>
</body>
</html>

dbs/gallery/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>DBS</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/master.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">DBS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'gallery:add' %}">Agregar Tarjeta</a>
      </li>
    </ul>
  </div>
</nav>

<main>
  <div class="container">
    <div class="row">
      {% for card in cards %}
        <div class="col">
          <div class="card my-2" style="width: 20rem;">
              <h4 class="card-title">{{ card.name }}</h4>
            {% if card.image %}
              <img class="card-img-top" src="{{ card.image.url }}" alt="Card image cap">
            {% else %}
              <img class="card-img-top" src="{% static 'images/dbs.jpg' %}" alt="Card image cap">
            {% endif %}
            <div class="card-body">
              <p class="card-text">{{ card.description }}</p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</main>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>